export const REASON_CODES = {
  KEEP_FORM_DIGITAL_SAME_COUNTRY: "KEEP_FORM_DIGITAL_SAME_COUNTRY",
  SEND_FORM_NON_DIGITAL_ISSUING_COUNTRY: "SEND_FORM_NON_DIGITAL_ISSUING_COUNTRY",
  SEND_FORM_CROSS_BORDER_DEPARTURE: "SEND_FORM_CROSS_BORDER_DEPARTURE",
  SEND_FORM_UNSUPPORTED_ROUTE: "SEND_FORM_UNSUPPORTED_ROUTE",
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
